//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2021Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2021Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104
        ///111
        ///124
        ///139
        ///142
        ///141
        ///144
        ///151
        ///152
        ///154
        ///157
        ///156
        ///157
        ///149
        ///123
        ///118
        ///129
        ///133
        ///134
        ///130
        ///124
        ///102
        ///103
        ///105
        ///104
        ///99
        ///100
        ///101
        ///103
        ///116
        ///114
        ///129
        ///135
        ///147
        ///149
        ///148
        ///149
        ///137
        ///140
        ///149
        ///159
        ///157
        ///159
        ///165
        ///164
        ///170
        ///176
        ///180
        ///192
        ///198
        ///200
        ///202
        ///203
        ///202
        ///211
        ///212
        ///230
        ///233
        ///237
        ///229
        ///226
        ///229
        ///234
        ///242
        ///245
        ///244
        ///242
        ///256
        ///258
        ///262
        ///267
        ///269
        ///285
        ///274
        ///279
        ///270
        ///302
        ///305
        ///308
        ///320
        ///323
        ///324
        ///323
        ///325
        ///358
        ///361
        ///367
        ///364
        ///363
        ///351
        ///352
        ///350
        ///349
        ///355
        ///356
        ///359
        ///367
        ///375
        ///405
        ///413
        ///417
        ///425
        ///428 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01Input {
            get {
                return ResourceManager.GetString("Day01Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1527.
        /// </summary>
        internal static string Day01Part1Output {
            get {
                return ResourceManager.GetString("Day01Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1575.
        /// </summary>
        internal static string Day01Part2Output {
            get {
                return ResourceManager.GetString("Day01Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward 6
        ///forward 6
        ///down 6
        ///down 5
        ///up 2
        ///forward 4
        ///forward 8
        ///up 9
        ///forward 3
        ///down 1
        ///forward 2
        ///forward 3
        ///down 1
        ///down 3
        ///down 3
        ///forward 9
        ///down 6
        ///forward 1
        ///up 5
        ///down 1
        ///forward 8
        ///forward 7
        ///up 8
        ///forward 7
        ///down 9
        ///forward 5
        ///forward 4
        ///forward 2
        ///down 3
        ///down 6
        ///down 6
        ///down 5
        ///forward 5
        ///forward 4
        ///forward 8
        ///up 3
        ///forward 6
        ///down 4
        ///up 2
        ///forward 8
        ///forward 6
        ///forward 1
        ///up 2
        ///down 9
        ///down 9
        ///up 5
        ///down 1
        ///up 1
        ///up 3
        ///forward 2
        ///forward 4
        ///down 8
        ///down 1
        ///up 1
        ///up 4
        ///up 1
        ///up 2
        ///forward 4
        ///d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02Input {
            get {
                return ResourceManager.GetString("Day02Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1815044.
        /// </summary>
        internal static string Day02Part1Output {
            get {
                return ResourceManager.GetString("Day02Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1739283308.
        /// </summary>
        internal static string Day02Part2Output {
            get {
                return ResourceManager.GetString("Day02Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 011111111100
        ///100001011111
        ///011010010010
        ///100110110110
        ///001000110001
        ///110010001010
        ///110000010010
        ///010110100110
        ///000101000110
        ///100101010010
        ///101000100011
        ///001100011000
        ///111100100011
        ///000000110111
        ///001000000010
        ///000000001110
        ///000000001001
        ///010111010000
        ///100010100010
        ///010110100000
        ///111111101001
        ///001011100001
        ///111011110110
        ///011010110011
        ///101110011011
        ///010100111101
        ///010100000011
        ///101001011000
        ///000011011100
        ///101101010000
        ///100110110011
        ///101001111001
        ///011111001100
        ///010110000100
        ///100000111011
        ///111110011110
        ///11001100 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03Input {
            get {
                return ResourceManager.GetString("Day03Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2250414.
        /// </summary>
        internal static string Day03Part1Output {
            get {
                return ResourceManager.GetString("Day03Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6085575.
        /// </summary>
        internal static string Day03Part2Output {
            get {
                return ResourceManager.GetString("Day03Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 69,88,67,56,53,97,46,29,37,51,3,93,92,78,41,22,45,66,13,82,2,7,52,40,18,70,32,95,89,64,84,68,83,26,43,0,61,36,57,34,80,39,6,63,72,98,21,54,23,28,65,16,76,11,20,33,96,4,10,25,30,19,90,24,55,91,15,8,71,99,58,14,60,48,44,17,47,85,74,87,86,27,42,38,81,79,94,73,12,5,77,35,9,62,50,31,49,59,75,1
        ///
        ///78 27 82 68 20
        ///14  2 34 51  7
        ///58 57 99 37 81
        /// 9  4  0 76 45
        ///67 69 70 17 23
        ///
        ///38 60 62 34 41
        ///39 58 91 45 10
        ///66 74 94 50 17
        ///68 27 75 97 49
        ///36 64  5 98 15
        ///
        ///17 50 13 53 20
        ///68 57 76 10 86
        /// 2 91 67 27 11
        ///94 70 8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04Input {
            get {
                return ResourceManager.GetString("Day04Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8580.
        /// </summary>
        internal static string Day04Part1Output {
            get {
                return ResourceManager.GetString("Day04Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9576.
        /// </summary>
        internal static string Day04Part2Output {
            get {
                return ResourceManager.GetString("Day04Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 309,347 -&gt; 309,464
        ///425,687 -&gt; 300,687
        ///226,766 -&gt; 885,107
        ///681,618 -&gt; 921,378
        ///968,54 -&gt; 38,984
        ///35,341 -&gt; 321,627
        ///493,485 -&gt; 632,485
        ///908,183 -&gt; 110,981
        ///677,378 -&gt; 677,231
        ///703,378 -&gt; 703,536
        ///179,581 -&gt; 429,331
        ///339,133 -&gt; 664,458
        ///212,680 -&gt; 212,136
        ///251,699 -&gt; 858,699
        ///163,725 -&gt; 163,22
        ///70,226 -&gt; 97,226
        ///968,119 -&gt; 954,119
        ///551,551 -&gt; 415,551
        ///768,167 -&gt; 546,167
        ///125,302 -&gt; 155,332
        ///640,201 -&gt; 341,201
        ///757,791 -&gt; 757,736
        ///406,570 -&gt; 418,558
        ///250,919 -&gt; 976,193
        ///570,362 -&gt; 304,96
        ///463,973 -&gt; 463,337        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day05Input {
            get {
                return ResourceManager.GetString("Day05Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6113.
        /// </summary>
        internal static string Day05Part1Output {
            get {
                return ResourceManager.GetString("Day05Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20373.
        /// </summary>
        internal static string Day05Part2Output {
            get {
                return ResourceManager.GetString("Day05Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,1,1,3,3,2,1,1,1,1,1,4,4,1,4,1,4,1,1,4,1,1,1,3,3,2,3,1,2,1,1,1,1,1,1,1,3,4,1,1,4,3,1,2,3,1,1,1,5,2,1,1,1,1,2,1,2,5,2,2,1,1,1,3,1,1,1,4,1,1,1,1,1,3,3,2,1,1,3,1,4,1,2,1,5,1,4,2,1,1,5,1,1,1,1,4,3,1,3,2,1,4,1,1,2,1,4,4,5,1,3,1,1,1,1,2,1,4,4,1,1,1,3,1,5,1,1,1,1,1,3,2,5,1,5,4,1,4,1,3,5,1,2,5,4,3,3,2,4,1,5,1,1,2,4,1,1,1,1,2,4,1,2,5,1,4,1,4,2,5,4,1,1,2,2,4,1,5,1,4,3,3,2,3,1,2,3,1,4,1,1,1,3,5,1,1,1,3,5,1,1,4,1,4,4,1,3,1,1,1,2,3,3,2,5,1,2,1,1,2,2,1,3,4,1,3,5,1,3,4,3,5,1,1,5,1,3,3,2,1,5,1,1,3,1,1,3,1,2,1,3,2,5,1,3,1, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day06Input {
            get {
                return ResourceManager.GetString("Day06Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day06Part1Output {
            get {
                return ResourceManager.GetString("Day06Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day06Part2Output {
            get {
                return ResourceManager.GetString("Day06Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1101,1,29,67,1102,0,1,65,1008,65,35,66,1005,66,28,1,67,65,20,4,0,1001,65,1,65,1106,0,8,99,35,67,101,99,105,32,110,39,101,115,116,32,112,97,115,32,117,110,101,32,105,110,116,99,111,100,101,32,112,114,111,103,114,97,109,10,273,102,514,428,300,13,9,457,92,169,1654,471,479,178,158,124,354,83,705,30,80,199,632,31,840,580,1228,1597,151,1374,1665,469,43,1113,103,1,1456,132,2,618,423,824,789,145,485,585,543,694,1266,866,1276,726,680,1714,503,79,137,208,8,1447,455,33,1098,1346,1028,178,1095,21,19,52,668,29,382,1659, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day07Input {
            get {
                return ResourceManager.GetString("Day07Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 344297.
        /// </summary>
        internal static string Day07Part1Output {
            get {
                return ResourceManager.GetString("Day07Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 97164301.
        /// </summary>
        internal static string Day07Part2Output {
            get {
                return ResourceManager.GetString("Day07Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gea agfcbe egcbfd aecb cegbf cafgde fgeba ea gabdf begfdca | bcfeg ea fbdga fbgcdae
        ///gbcd gce fedgba edafgc cafbe febgc febgcd cg egbdf dgcefab | ceg cfdgae bdcg cdgfbe
        ///eaf cfade afgebc cdegfa abcfd feagcdb dfbgce ae dcefg dage | eaf cdgefb fea bfacd
        ///faegbdc fagcde dbcfg ecgfb afegc gbe abec bgfcea eb befagd | afcge egb cgfbd bace
        ///caegb fcaged ce gafcb gfcabe egdfcba acdfbg eca dbgea bcfe | gedbcaf ec ce fegacbd
        ///bcegad beag agcbd ged degcabf dcaegf fecdb eg dbgfca dgbec | gcdebaf gde bacgd egcdaf
        ///cbgef [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day08Input {
            get {
                return ResourceManager.GetString("Day08Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 445.
        /// </summary>
        internal static string Day08Part1Output {
            get {
                return ResourceManager.GetString("Day08Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1043101.
        /// </summary>
        internal static string Day08Part2Output {
            get {
                return ResourceManager.GetString("Day08Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0197653456789987679545987978921245689901497654212455689767899878999979653246892123569876467899212346
        ///9989542349899986578959976557890134599892398943201234678956789467989867932135789012398764345678923456
        ///8679931298999765459898765445921247987689459865432345889345892399876546899013894123459976569799634577
        ///6567895497998764345789543239895456797535967976545467891234989989865434598954993248969987678999545798
        ///8456897986539975234568955398789967998212899597676578910395678979996423987895789356798698799997656789
        ///73 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day09Input {
            get {
                return ResourceManager.GetString("Day09Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 585.
        /// </summary>
        internal static string Day09Part1Output {
            get {
                return ResourceManager.GetString("Day09Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day09Part2Output {
            get {
                return ResourceManager.GetString("Day09Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {[&lt;([&lt;[[(&lt;[({&lt;&lt;&gt;&lt;&gt;&gt;&lt;()[]&gt;}&lt;(()())(())&gt;)&lt;(([]())){&lt;()()&gt;&lt;{}&lt;&gt;)}&gt;][(((()&lt;&gt;)[{}{}]){&lt;[]&lt;&gt;&gt;({}{})})]&gt;)[(({([{}[]]
        ///{{[[(&lt;[[[&lt;[&lt;&lt;{()()}(&lt;&gt;{})&gt;[&lt;&lt;&gt;&lt;&gt;&gt;[[]]]&gt;[{{[]&lt;&gt;}[[]]}&lt;&lt;[]{}&gt;[&lt;&gt;[]]&gt;]]([[[{}&lt;&gt;]]&lt;&lt;()[]&gt;{()&lt;&gt;}&gt;]([&lt;&lt;
        ///([&lt;{[[{{((([(&lt;[]&lt;&gt;&gt;{[]&lt;&gt;})&lt;([]){&lt;&gt;{}}&gt;][([&lt;&gt;[]][[]{}])])[[{{()[]}&lt;()[]&gt;}&lt;{(){}}&gt;]]]&lt;{(&lt;[{}&lt;
        ///(({(&lt;{(([&lt;[({([]())(&lt;&gt;())}{([]{})[{}{}]})]{(({{}()}{&lt;&gt;()}](&lt;[]&lt;&gt;&gt;(()[])))({[[]{}]&lt;[]&lt;&gt;&gt;})}&gt;[[[{&lt;&lt;&gt;[]&gt;(()
        ///[([&lt;([{({{[{[([]{})[{}[]]][[{}{})]}&lt;([&lt;&gt;{}]&lt;&lt;&gt;()&gt;)&gt;]}([&lt;{[()&lt;&gt;]{()&lt;&gt;}}[[{}{}]&lt;(){}&gt;]&gt;&lt;{{{}[]}[()&lt;&gt;]}[{{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day10Input {
            get {
                return ResourceManager.GetString("Day10Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 294195.
        /// </summary>
        internal static string Day10Part1Output {
            get {
                return ResourceManager.GetString("Day10Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3490802734.
        /// </summary>
        internal static string Day10Part2Output {
            get {
                return ResourceManager.GetString("Day10Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3265255276
        ///1537412665
        ///7335746422
        ///6426325658
        ///3854434364
        ///8717377486
        ///4522286326
        ///6337772845
        ///8824387665
        ///6351586484.
        /// </summary>
        internal static string Day11Input {
            get {
                return ResourceManager.GetString("Day11Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1627.
        /// </summary>
        internal static string Day11Part1Output {
            get {
                return ResourceManager.GetString("Day11Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 329.
        /// </summary>
        internal static string Day11Part2Output {
            get {
                return ResourceManager.GetString("Day11Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day12Input {
            get {
                return ResourceManager.GetString("Day12Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day12Part1Output {
            get {
                return ResourceManager.GetString("Day12Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day12Part2Output {
            get {
                return ResourceManager.GetString("Day12Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 957,648
        ///617,33
        ///915,323
        ///760,515
        ///82,365
        ///1206,634
        ///959,231
        ///74,324
        ///552,785
        ///597,740
        ///33,226
        ///765,871
        ///1195,407
        ///1036,653
        ///308,789
        ///880,337
        ///550,379
        ///1084,71
        ///750,308
        ///914,227
        ///922,861
        ///492,569
        ///1300,796
        ///570,301
        ///366,379
        ///252,794
        ///340,424
        ///1019,550
        ///443,407
        ///1298,22
        ///216,179
        ///713,740
        ///492,325
        ///736,284
        ///1004,589
        ///716,189
        ///293,205
        ///560,751
        ///396,59
        ///1102,415
        ///398,396
        ///750,695
        ///584,765
        ///1143,849
        ///398,834
        ///28,213
        ///291,446
        ///587,327
        ///582,376
        ///798,393
        ///126,826
        ///422,527
        ///274,345
        ///877,873
        ///684,661
        ///1118,36
        ///348,44 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day13Input {
            get {
                return ResourceManager.GetString("Day13Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 735.
        /// </summary>
        internal static string Day13Part1Output {
            get {
                return ResourceManager.GetString("Day13Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99.
        /// </summary>
        internal static string Day13Part2Output {
            get {
                return ResourceManager.GetString("Day13Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day14Input {
            get {
                return ResourceManager.GetString("Day14Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day14Part1Output {
            get {
                return ResourceManager.GetString("Day14Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day14Part2Output {
            get {
                return ResourceManager.GetString("Day14Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day15Input {
            get {
                return ResourceManager.GetString("Day15Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day15Part1Output {
            get {
                return ResourceManager.GetString("Day15Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day15Part2Output {
            get {
                return ResourceManager.GetString("Day15Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day16Input {
            get {
                return ResourceManager.GetString("Day16Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day16Part1Output {
            get {
                return ResourceManager.GetString("Day16Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day16Part2Output {
            get {
                return ResourceManager.GetString("Day16Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day17Input {
            get {
                return ResourceManager.GetString("Day17Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day17Part1Output {
            get {
                return ResourceManager.GetString("Day17Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day17Part2Output {
            get {
                return ResourceManager.GetString("Day17Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day18Input {
            get {
                return ResourceManager.GetString("Day18Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day18Part1Output {
            get {
                return ResourceManager.GetString("Day18Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day18Part2Output {
            get {
                return ResourceManager.GetString("Day18Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day19Input {
            get {
                return ResourceManager.GetString("Day19Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day19Part1Output {
            get {
                return ResourceManager.GetString("Day19Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day19Part2Output {
            get {
                return ResourceManager.GetString("Day19Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day20Input {
            get {
                return ResourceManager.GetString("Day20Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day20Part1Output {
            get {
                return ResourceManager.GetString("Day20Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day20Part2Output {
            get {
                return ResourceManager.GetString("Day20Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day21Input {
            get {
                return ResourceManager.GetString("Day21Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day21Part1Output {
            get {
                return ResourceManager.GetString("Day21Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day21Part2Output {
            get {
                return ResourceManager.GetString("Day21Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day22Input {
            get {
                return ResourceManager.GetString("Day22Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day22Part1Output {
            get {
                return ResourceManager.GetString("Day22Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day22Part2Output {
            get {
                return ResourceManager.GetString("Day22Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day23Input {
            get {
                return ResourceManager.GetString("Day23Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day23Part1Output {
            get {
                return ResourceManager.GetString("Day23Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day23Part2Output {
            get {
                return ResourceManager.GetString("Day23Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day24Input {
            get {
                return ResourceManager.GetString("Day24Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day24Part1Output {
            get {
                return ResourceManager.GetString("Day24Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day24Part2Output {
            get {
                return ResourceManager.GetString("Day24Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day25Input {
            get {
                return ResourceManager.GetString("Day25Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day25Part1Output {
            get {
                return ResourceManager.GetString("Day25Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day25Part2Output {
            get {
                return ResourceManager.GetString("Day25Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string DayXXInput {
            get {
                return ResourceManager.GetString("DayXXInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string DayXXPart1Output {
            get {
                return ResourceManager.GetString("DayXXPart1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string DayXXPart2Output {
            get {
                return ResourceManager.GetString("DayXXPart2Output", resourceCulture);
            }
        }
    }
}
