//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2021Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2021Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104
        ///111
        ///124
        ///139
        ///142
        ///141
        ///144
        ///151
        ///152
        ///154
        ///157
        ///156
        ///157
        ///149
        ///123
        ///118
        ///129
        ///133
        ///134
        ///130
        ///124
        ///102
        ///103
        ///105
        ///104
        ///99
        ///100
        ///101
        ///103
        ///116
        ///114
        ///129
        ///135
        ///147
        ///149
        ///148
        ///149
        ///137
        ///140
        ///149
        ///159
        ///157
        ///159
        ///165
        ///164
        ///170
        ///176
        ///180
        ///192
        ///198
        ///200
        ///202
        ///203
        ///202
        ///211
        ///212
        ///230
        ///233
        ///237
        ///229
        ///226
        ///229
        ///234
        ///242
        ///245
        ///244
        ///242
        ///256
        ///258
        ///262
        ///267
        ///269
        ///285
        ///274
        ///279
        ///270
        ///302
        ///305
        ///308
        ///320
        ///323
        ///324
        ///323
        ///325
        ///358
        ///361
        ///367
        ///364
        ///363
        ///351
        ///352
        ///350
        ///349
        ///355
        ///356
        ///359
        ///367
        ///375
        ///405
        ///413
        ///417
        ///425
        ///428 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01Input {
            get {
                return ResourceManager.GetString("Day01Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1527.
        /// </summary>
        internal static string Day01Part1Output {
            get {
                return ResourceManager.GetString("Day01Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1575.
        /// </summary>
        internal static string Day01Part2Output {
            get {
                return ResourceManager.GetString("Day01Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward 6
        ///forward 6
        ///down 6
        ///down 5
        ///up 2
        ///forward 4
        ///forward 8
        ///up 9
        ///forward 3
        ///down 1
        ///forward 2
        ///forward 3
        ///down 1
        ///down 3
        ///down 3
        ///forward 9
        ///down 6
        ///forward 1
        ///up 5
        ///down 1
        ///forward 8
        ///forward 7
        ///up 8
        ///forward 7
        ///down 9
        ///forward 5
        ///forward 4
        ///forward 2
        ///down 3
        ///down 6
        ///down 6
        ///down 5
        ///forward 5
        ///forward 4
        ///forward 8
        ///up 3
        ///forward 6
        ///down 4
        ///up 2
        ///forward 8
        ///forward 6
        ///forward 1
        ///up 2
        ///down 9
        ///down 9
        ///up 5
        ///down 1
        ///up 1
        ///up 3
        ///forward 2
        ///forward 4
        ///down 8
        ///down 1
        ///up 1
        ///up 4
        ///up 1
        ///up 2
        ///forward 4
        ///d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02Input {
            get {
                return ResourceManager.GetString("Day02Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1815044.
        /// </summary>
        internal static string Day02Part1Output {
            get {
                return ResourceManager.GetString("Day02Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1739283308.
        /// </summary>
        internal static string Day02Part2Output {
            get {
                return ResourceManager.GetString("Day02Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 011111111100
        ///100001011111
        ///011010010010
        ///100110110110
        ///001000110001
        ///110010001010
        ///110000010010
        ///010110100110
        ///000101000110
        ///100101010010
        ///101000100011
        ///001100011000
        ///111100100011
        ///000000110111
        ///001000000010
        ///000000001110
        ///000000001001
        ///010111010000
        ///100010100010
        ///010110100000
        ///111111101001
        ///001011100001
        ///111011110110
        ///011010110011
        ///101110011011
        ///010100111101
        ///010100000011
        ///101001011000
        ///000011011100
        ///101101010000
        ///100110110011
        ///101001111001
        ///011111001100
        ///010110000100
        ///100000111011
        ///111110011110
        ///11001100 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03Input {
            get {
                return ResourceManager.GetString("Day03Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2250414.
        /// </summary>
        internal static string Day03Part1Output {
            get {
                return ResourceManager.GetString("Day03Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6085575.
        /// </summary>
        internal static string Day03Part2Output {
            get {
                return ResourceManager.GetString("Day03Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 69,88,67,56,53,97,46,29,37,51,3,93,92,78,41,22,45,66,13,82,2,7,52,40,18,70,32,95,89,64,84,68,83,26,43,0,61,36,57,34,80,39,6,63,72,98,21,54,23,28,65,16,76,11,20,33,96,4,10,25,30,19,90,24,55,91,15,8,71,99,58,14,60,48,44,17,47,85,74,87,86,27,42,38,81,79,94,73,12,5,77,35,9,62,50,31,49,59,75,1
        ///
        ///78 27 82 68 20
        ///14  2 34 51  7
        ///58 57 99 37 81
        /// 9  4  0 76 45
        ///67 69 70 17 23
        ///
        ///38 60 62 34 41
        ///39 58 91 45 10
        ///66 74 94 50 17
        ///68 27 75 97 49
        ///36 64  5 98 15
        ///
        ///17 50 13 53 20
        ///68 57 76 10 86
        /// 2 91 67 27 11
        ///94 70 8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day04Input {
            get {
                return ResourceManager.GetString("Day04Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8580.
        /// </summary>
        internal static string Day04Part1Output {
            get {
                return ResourceManager.GetString("Day04Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9576.
        /// </summary>
        internal static string Day04Part2Output {
            get {
                return ResourceManager.GetString("Day04Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day05Input {
            get {
                return ResourceManager.GetString("Day05Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day05Part1Output {
            get {
                return ResourceManager.GetString("Day05Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day05Part2Output {
            get {
                return ResourceManager.GetString("Day05Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day06Input {
            get {
                return ResourceManager.GetString("Day06Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day06Part1Output {
            get {
                return ResourceManager.GetString("Day06Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day06Part2Output {
            get {
                return ResourceManager.GetString("Day06Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day07Input {
            get {
                return ResourceManager.GetString("Day07Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day07Part1Output {
            get {
                return ResourceManager.GetString("Day07Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day07Part2Output {
            get {
                return ResourceManager.GetString("Day07Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day08Input {
            get {
                return ResourceManager.GetString("Day08Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day08Part1Output {
            get {
                return ResourceManager.GetString("Day08Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day08Part2Output {
            get {
                return ResourceManager.GetString("Day08Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day09Input {
            get {
                return ResourceManager.GetString("Day09Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day09Part1Output {
            get {
                return ResourceManager.GetString("Day09Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day09Part2Output {
            get {
                return ResourceManager.GetString("Day09Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day10Input {
            get {
                return ResourceManager.GetString("Day10Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day10Part1Output {
            get {
                return ResourceManager.GetString("Day10Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day10Part2Output {
            get {
                return ResourceManager.GetString("Day10Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day11Input {
            get {
                return ResourceManager.GetString("Day11Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day11Part1Output {
            get {
                return ResourceManager.GetString("Day11Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day11Part2Output {
            get {
                return ResourceManager.GetString("Day11Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day12Input {
            get {
                return ResourceManager.GetString("Day12Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day12Part1Output {
            get {
                return ResourceManager.GetString("Day12Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day12Part2Output {
            get {
                return ResourceManager.GetString("Day12Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day13Input {
            get {
                return ResourceManager.GetString("Day13Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day13Part1Output {
            get {
                return ResourceManager.GetString("Day13Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day13Part2Output {
            get {
                return ResourceManager.GetString("Day13Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day14Input {
            get {
                return ResourceManager.GetString("Day14Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day14Part1Output {
            get {
                return ResourceManager.GetString("Day14Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day14Part2Output {
            get {
                return ResourceManager.GetString("Day14Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day15Input {
            get {
                return ResourceManager.GetString("Day15Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day15Part1Output {
            get {
                return ResourceManager.GetString("Day15Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day15Part2Output {
            get {
                return ResourceManager.GetString("Day15Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day16Input {
            get {
                return ResourceManager.GetString("Day16Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day16Part1Output {
            get {
                return ResourceManager.GetString("Day16Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day16Part2Output {
            get {
                return ResourceManager.GetString("Day16Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day17Input {
            get {
                return ResourceManager.GetString("Day17Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day17Part1Output {
            get {
                return ResourceManager.GetString("Day17Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day17Part2Output {
            get {
                return ResourceManager.GetString("Day17Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day18Input {
            get {
                return ResourceManager.GetString("Day18Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day18Part1Output {
            get {
                return ResourceManager.GetString("Day18Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day18Part2Output {
            get {
                return ResourceManager.GetString("Day18Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day19Input {
            get {
                return ResourceManager.GetString("Day19Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day19Part1Output {
            get {
                return ResourceManager.GetString("Day19Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day19Part2Output {
            get {
                return ResourceManager.GetString("Day19Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day20Input {
            get {
                return ResourceManager.GetString("Day20Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day20Part1Output {
            get {
                return ResourceManager.GetString("Day20Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day20Part2Output {
            get {
                return ResourceManager.GetString("Day20Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day21Input {
            get {
                return ResourceManager.GetString("Day21Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day21Part1Output {
            get {
                return ResourceManager.GetString("Day21Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day21Part2Output {
            get {
                return ResourceManager.GetString("Day21Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day22Input {
            get {
                return ResourceManager.GetString("Day22Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day22Part1Output {
            get {
                return ResourceManager.GetString("Day22Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day22Part2Output {
            get {
                return ResourceManager.GetString("Day22Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day23Input {
            get {
                return ResourceManager.GetString("Day23Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day23Part1Output {
            get {
                return ResourceManager.GetString("Day23Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day23Part2Output {
            get {
                return ResourceManager.GetString("Day23Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day24Input {
            get {
                return ResourceManager.GetString("Day24Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day24Part1Output {
            get {
                return ResourceManager.GetString("Day24Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day24Part2Output {
            get {
                return ResourceManager.GetString("Day24Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day25Input {
            get {
                return ResourceManager.GetString("Day25Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day25Part1Output {
            get {
                return ResourceManager.GetString("Day25Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string Day25Part2Output {
            get {
                return ResourceManager.GetString("Day25Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string DayXXInput {
            get {
                return ResourceManager.GetString("DayXXInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string DayXXPart1Output {
            get {
                return ResourceManager.GetString("DayXXPart1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string DayXXPart2Output {
            get {
                return ResourceManager.GetString("DayXXPart2Output", resourceCulture);
            }
        }
    }
}
