//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2021Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2021Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 104
        ///111
        ///124
        ///139
        ///142
        ///141
        ///144
        ///151
        ///152
        ///154
        ///157
        ///156
        ///157
        ///149
        ///123
        ///118
        ///129
        ///133
        ///134
        ///130
        ///124
        ///102
        ///103
        ///105
        ///104
        ///99
        ///100
        ///101
        ///103
        ///116
        ///114
        ///129
        ///135
        ///147
        ///149
        ///148
        ///149
        ///137
        ///140
        ///149
        ///159
        ///157
        ///159
        ///165
        ///164
        ///170
        ///176
        ///180
        ///192
        ///198
        ///200
        ///202
        ///203
        ///202
        ///211
        ///212
        ///230
        ///233
        ///237
        ///229
        ///226
        ///229
        ///234
        ///242
        ///245
        ///244
        ///242
        ///256
        ///258
        ///262
        ///267
        ///269
        ///285
        ///274
        ///279
        ///270
        ///302
        ///305
        ///308
        ///320
        ///323
        ///324
        ///323
        ///325
        ///358
        ///361
        ///367
        ///364
        ///363
        ///351
        ///352
        ///350
        ///349
        ///355
        ///356
        ///359
        ///367
        ///375
        ///405
        ///413
        ///417
        ///425
        ///428 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01Input {
            get {
                return ResourceManager.GetString("Day01Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1527.
        /// </summary>
        internal static string Day01Part1Output {
            get {
                return ResourceManager.GetString("Day01Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1575.
        /// </summary>
        internal static string Day01Part2Output {
            get {
                return ResourceManager.GetString("Day01Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward 6
        ///forward 6
        ///down 6
        ///down 5
        ///up 2
        ///forward 4
        ///forward 8
        ///up 9
        ///forward 3
        ///down 1
        ///forward 2
        ///forward 3
        ///down 1
        ///down 3
        ///down 3
        ///forward 9
        ///down 6
        ///forward 1
        ///up 5
        ///down 1
        ///forward 8
        ///forward 7
        ///up 8
        ///forward 7
        ///down 9
        ///forward 5
        ///forward 4
        ///forward 2
        ///down 3
        ///down 6
        ///down 6
        ///down 5
        ///forward 5
        ///forward 4
        ///forward 8
        ///up 3
        ///forward 6
        ///down 4
        ///up 2
        ///forward 8
        ///forward 6
        ///forward 1
        ///up 2
        ///down 9
        ///down 9
        ///up 5
        ///down 1
        ///up 1
        ///up 3
        ///forward 2
        ///forward 4
        ///down 8
        ///down 1
        ///up 1
        ///up 4
        ///up 1
        ///up 2
        ///forward 4
        ///d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02Input {
            get {
                return ResourceManager.GetString("Day02Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1815044.
        /// </summary>
        internal static string Day02Part1Output {
            get {
                return ResourceManager.GetString("Day02Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1739283308.
        /// </summary>
        internal static string Day02Part2Output {
            get {
                return ResourceManager.GetString("Day02Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 011111111100
        ///100001011111
        ///011010010010
        ///100110110110
        ///001000110001
        ///110010001010
        ///110000010010
        ///010110100110
        ///000101000110
        ///100101010010
        ///101000100011
        ///001100011000
        ///111100100011
        ///000000110111
        ///001000000010
        ///000000001110
        ///000000001001
        ///010111010000
        ///100010100010
        ///010110100000
        ///111111101001
        ///001011100001
        ///111011110110
        ///011010110011
        ///101110011011
        ///010100111101
        ///010100000011
        ///101001011000
        ///000011011100
        ///101101010000
        ///100110110011
        ///101001111001
        ///011111001100
        ///010110000100
        ///100000111011
        ///111110011110
        ///11001100 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03Input {
            get {
                return ResourceManager.GetString("Day03Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2250414.
        /// </summary>
        internal static string Day03Part1Output {
            get {
                return ResourceManager.GetString("Day03Part1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6085575.
        /// </summary>
        internal static string Day03Part2Output {
            get {
                return ResourceManager.GetString("Day03Part2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string DayXXInput {
            get {
                return ResourceManager.GetString("DayXXInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string DayXXPart1Output {
            get {
                return ResourceManager.GetString("DayXXPart1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string DayXXPart2Output {
            get {
                return ResourceManager.GetString("DayXXPart2Output", resourceCulture);
            }
        }
    }
}
